const {readFileSync}=require('node:fs');
const {join}=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const context={};vm.createContext(context);
vm.runInContext(readFileSync(join(__dirname,'../web/shape.js'),'utf8'),context);
vm.runInContext(`
 const points={};
 VPA_INNER.forEach((id,i)=>{const a=i*2*Math.PI/20;points[id]=[.3*Math.cos(a),.1*Math.sin(a)];});
 points[61]=[-.4,0];points[291]=[.4,0];points[0]=[0,-.2];points[17]=[0,.2];
 const frame={quality:{status:'observed'},landmarks:points};
 globalThis.result=shapeMeasurements(frame);
 const transformed=Object.fromEntries(Object.entries(points).map(([id,[x,y]])=>[id,[3*(-y)+4,3*x-7]]));
 globalThis.transformed=shapeMeasurements({...frame,landmarks:transformed});
 globalThis.missing=shapeMeasurements({...frame,quality:{status:'missing'}});
 globalThis.zeroWidth=shapeMeasurements({...frame,landmarks:{...points,291:points[61]}});
 globalThis.old=shapeMeasurements({...frame,landmarks:{0:points[0],13:points[13],14:points[14],17:points[17]}});
`,context);
const {result:r,transformed:t}=context;
assert(Math.abs(r.opening_area-10*.3*.1*Math.sin(Math.PI/10))<1e-10);
assert(Math.abs(t.opening_area-9*r.opening_area)<1e-10);
assert(Math.abs(t.opening_area_ratio-r.opening_area_ratio)<1e-10);
assert(Math.abs(t.side_gap_61-3*r.side_gap_61)<1e-10);
assert(Object.values(context.missing).every(v=>v===null));
assert.equal(context.zeroWidth.opening_area_ratio,null);
assert.equal(context.zeroWidth.gap_asymmetry,null);
assert.equal(context.old.opening_area,null);
assert.notEqual(context.old.upper_lip_thickness,null);
console.log('Shape measurements: known area, transform invariance, missing data, zero width, legacy landmarks passed.');
